<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Student Control</title>
		<link rel="stylesheet" type="text/css" href="css/style_index.css"/>
	</head>
	<body>
		
		<!-- header -->	

		<header id="header">
			<section id="title">
				<a href="/">
					<h2>Student Control</h2>
				</a>
			</section>
			<section id="menu">
				<ul>
					<li><a href="/register">Register</a></li>
					<li><a href="/login">Login</a></li>
				</ul>
			</section>
		</header>

		<!-- fim header -->

		<!-- presentation -->

		<section id="presentation">
			<section id="social">
				<img src="img/linkedin.png" alt="linkedin" width="30" height="30" />
				<h3>&nbsp;&nbsp;
					<a href="https://www.linkedin.com/in/katarine-albuquerque-b0967a51/">
						My Linkedin
					</a>
				</h3>
				<h4>&nbsp;&nbsp;@kba 2020</h4>
			</section>
			<section id="description">
				<h4>Student Control platform created for students to follow their work and exams with their respective grades.</h4>
			</section>
		</section>
		
		<!-- fim presentation -->

	</body>
</html>