<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Student Control</title>
		<link rel="stylesheet" type="text/css" href="css/style_index.css"/>
		<link rel="stylesheet" type="text/css" href="css/style_login.css"/>
	</head>
	<body>
		
		<!-- header -->	

		<header id="header">
			<section id="title">
				<a href="/">
					<h2>Student Control</h2>
				</a>
			</section>
		</header>

		<!-- fim header -->

		<!-- login -->

		<section id="login">
			<form method="post" action="/auth_login">
				<h2>Login</h2>
				<input type="email" name="email" placeholder="E-mail"/>
				<input type="password" name="password" placeholder="Password">
				<input id="btn" type="submit" value="LOGIN"/>
			<?php if($this->view->login == 'error') { ?>
				<h4>Error authenticating data, email or incorrect password(s)</h4>
			<?php } ?>
			</form>		
		</section>
		
		<!-- fim login -->

	</body>
</html>