<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Student Control</title>
		<link rel="stylesheet" type="text/css" href="css/style_index.css"/>
		<link rel="stylesheet" type="text/css" href="css/style_success.css"/>
	</head>
	<body>
		
		<!-- header -->	

		<header id="header">
			<section id="title">
				<a href="/">
					<h2>Student Control</h2>
				</a>
			</section>
		</header>

		<!-- fim header -->

		<!-- success -->

		<section id="success">
			<section id="content">
				<h1>Success</h1>
				<p>Data saved successfully!</p>
				<div id="link_login">
					<a href="/login">Access your login</a>
				</div>
			</section>			
		</section>
		
		<!-- fim success -->

	</body>
</html>